### ISSUE TITLE
FOR FUNCTION MODE

### ISSUE THREAD

**Issue by HongwenFang** [mawady/bus-segmentation#1]
Hi ! How can I get the v1_kmeans and v1_quickseg function? Thank you!

**Comment by mawady** [comment]
You need to use vl_feat library to be able to use these functions (vl_kmeans, vl_quickseg).
That's why i added the following code line:
`run('C:\MATLAB_libs\vlfeat\vlfeat-0.9.20\toolbox\vl_setup');`

**Comment by HongwenFang** [comment]
I have got them. Thank you very much!
